apiVersion: v1
kind: Pod
metadata:
  name: valid-pod
spec:
  containers:
  - name: valid-pod
    image: alpine:latest

---
apiVersion: v1
kind: Pod
metadata:
  name: invalid-pod
spec:
  containers:
  - name: invalid-pod
    image: alpine:latest
  volumes:
  - name: hostpath-volume
    hostPath:
      path: /etc
