apiVersion: v1
kind: Pod
metadata:
  name: valid-pod
spec:
  containers:
  - name: valid-pod
    image: alpine:latest
    command:
      - "sleep"
      - "1"
---
apiVersion: v1
kind: Pod
metadata:
  name: invalid-pod
spec:
  containers:
  - name: invalid-pod
    image: alpine:latest
    command:
      - "sleep"
      - "1"
  volumes:
  - name: hostpath-volume
    hostPath:
      path: /etc